/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_calit2_mooc_iot_db410c_webserver_WebServer */

#ifndef _Included_net_calit2_mooc_iot_db410c_webserver_WebServer
#define _Included_net_calit2_mooc_iot_db410c_webserver_WebServer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_calit2_mooc_iot_db410c_webserver_WebServer_REFRESH_RATE
#define net_calit2_mooc_iot_db410c_webserver_WebServer_REFRESH_RATE 5000L
/*
 * Class:     net_calit2_mooc_iot_db410c_webserver_WebServer
 * Method:    beginServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_calit2_mooc_iot_1db410c_webserver_WebServer_beginServer
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
